export const PERMISSIONS = {
  "records.view": true,
  "records.create": true,
  "records.edit": true,
  "records.delete": true,
  "records.export": true,
  "records.bulk_delete": true,
  "fields.view": true,
  "fields.manage": true,
  "users.view": true,
  "users.invite": true,
  "users.manage": true,
  "users.remove": true,
  "audit.view": true,
  "settings.view": true,
  "settings.manage": true,
  "pipeline.view": true,
  "pipeline.manage": true,
  "chat.view": true,
  "chat.send": true,
  "templates.view": true,
  "templates.manage": true,
  "billing.view": true,
  "billing.manage": true,
} as const;

export type PermissionKey = keyof typeof PERMISSIONS;

export const ROLE_PERMISSIONS: Record<string, Record<PermissionKey, boolean>> = {
  admin: Object.fromEntries(Object.keys(PERMISSIONS).map((k) => [k, true])) as Record<PermissionKey, boolean>,
  manager: {
    "records.view": true,
    "records.create": true,
    "records.edit": true,
    "records.delete": true,
    "records.export": true,
    "records.bulk_delete": false,
    "fields.view": true,
    "fields.manage": false,
    "users.view": true,
    "users.invite": true,
    "users.manage": false,
    "users.remove": false,
    "audit.view": true,
    "settings.view": true,
    "settings.manage": false,
    "pipeline.view": true,
    "pipeline.manage": true,
    "chat.view": true,
    "chat.send": true,
    "templates.view": true,
    "templates.manage": true,
    "billing.view": false,
    "billing.manage": false,
  },
  employee: {
    "records.view": true,
    "records.create": true,
    "records.edit": true,
    "records.delete": false,
    "records.export": false,
    "records.bulk_delete": false,
    "fields.view": true,
    "fields.manage": false,
    "users.view": true,
    "users.invite": false,
    "users.manage": false,
    "users.remove": false,
    "audit.view": false,
    "settings.view": false,
    "settings.manage": false,
    "pipeline.view": true,
    "pipeline.manage": false,
    "chat.view": true,
    "chat.send": true,
    "templates.view": true,
    "templates.manage": false,
    "billing.view": false,
    "billing.manage": false,
  },
  viewer: {
    "records.view": true,
    "records.create": false,
    "records.edit": false,
    "records.delete": false,
    "records.export": false,
    "records.bulk_delete": false,
    "fields.view": true,
    "fields.manage": false,
    "users.view": true,
    "users.invite": false,
    "users.manage": false,
    "users.remove": false,
    "audit.view": false,
    "settings.view": false,
    "settings.manage": false,
    "pipeline.view": true,
    "pipeline.manage": false,
    "chat.view": true,
    "chat.send": false,
    "templates.view": true,
    "templates.manage": false,
    "billing.view": false,
    "billing.manage": false,
  },
};

export function hasPermission(
  userPermissions: Record<string, boolean>,
  permission: PermissionKey
): boolean {
  return userPermissions[permission] === true;
}
